const types = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FINISHED: 'LOGIN_FINISHED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_EDIT: 'LOGIN_EDIT',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_FINISHED: 'LOGOUT_FINISHED',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  APP_INIT: 'APP_INIT',
  USER_EDIT: 'USER_EDIT',
  USER_EDIT_FAIL: 'USER_EDIT_FAIL',
  USER_SAVE: 'USER_SAVE',
  REMOVE_USER: 'REMOVE_USER',
  USER_WORKSPACE: 'USER_WORKSPACE',
  FETCH_PETS:'FETCH_PETS',
  SAVE_PETS: 'SAVE_PETS',
  NOTIFICATION_RECIEVED: 'NOTIFICATION_RECIEVED',
  SAVE_POST_ID: 'SAVE_POST_ID',
  SHOW_CONFETTI:'SHOW_CONFETTI',
  NEWS_FEED:'NEWS_FEED',
  NEWS_FEED_SUCCESSFUL:'NEWS_FEED_SUCCESSFUL',
  NEWS_FEED_FAIL:'NEWS_FEED_FAIL',
  OWNER_STORIES:'OWNER_STORIES',
  OWNER_FRIEND_SUGGESTION:'OWNER_FRIEND_SUGGESTION',
  POST_REACTION:'POST_REACTION',
  CREATE_NEW_POST:'CREATE_NEW_POST',
  CREATE_NEW_POST_SUCCESSFUL:'CREATE_NEW_POST_SUCCESSFUL',
  CREATE_NEW_POST_FAIL:'CREATE_NEW_POST_FAIL',
  FOLLOWS_FOLLOWERS:'FOLLOWS_FOLLOWERS',
  PET_PROFILE :'PET_PROFILE',
  GIFT_TAG:'GIFT_TAG',
  PRODUCT:'PRODUCT',
  CART_DATA:'CART_DATA',
  ORDER_NATURE:'ORDER_NATURE',
  IS_FREE_ORDER:'FREE_OREDER',
  UPDATE_POST_SHARE_COUNT:' UPDATE_POST_SHARE_COUNT',
  PERSIST_TOKEN:'PERSIST_TOKEN',
  GET_UPDATED_PET_DATA:' GET_UPDATED_PET_DATA',
  BEFORE_POST_ID : 'BEFORE_POST_ID'

};

export const pagesTypes={
  OWNER_PAGES:'GET_OWNER_PAGES',
  OWNER_PAGES_SUCCESSFULL:'OWNER_PAGES_SUCCESSFULL',
  OWNER_LIKED_PAGES:'OWNER_LIKED_PAGES',
  OWNER_RECOMMEND_PAGES:'OWNER_RECOMMEND_PAGES',
  OWNER_LIKE_PAGE:'OWNER_LIKE_PAGE',
  OWNER_LIKE_PAGE_SUCCESSFUL:'OWNER_LIKE_PAGE_SUCCESSFUL',
  OWNER_PAGE_NEWSFEED:'OWNER_PAGE_NEWSFEED',
  OWNER_PAGE_NEWSFEED_SUCCESSFUL:'OWNER_PAGE_NEWSFEED_SUCCESSFUL',
  OWNER_PAGE_NEWSFEED_FAIL:'OWNER_PAGE_NEWSFEED_FAIL',
  DELETE_PAGE:'DELETE_PAGE',
  CREATE_PAGE:'CREATE_PAGE',
  CREATE_PAGE_SUCCESSFUL:'CREATE_PAGE_SUCCESSFUL',
  CREATE_PAGE_FAIL:' CREATE_PAGE_FAIL'


}
export const groupTypes={
  OWNER_GROUPS:'GET_OWNER_GROUPS',
  OWNER_GROUPS_SUCCESSFULL:'OWNER_GROUPS_SUCCESSFULL',
  OWNER_RECOMMEND_GROUPS_SUCCESSFUL:'OWNER_RECOMMEND_GROUPS_SUCCESSFUL',
  OWNER_JOINED_GROUP:'OWNER_JOINED_GROUP',
  OWNER_JOINED_GROUP_SUCCESSFUL:'OWNER_JOINED_GROUP_SUCCESSFUL',
  OWNER_GROUP_NEWSFEED:'OWNER_GROUP_NEWSFEED',
  OWNER_GROUP_NEWSFEED_SUCCESSFUL:'OWNER_GROUP_NEWSFEED_SUCCESSFUL',
  OWNER_GROUP_NEWSFEED_FAIL:'OWNER_GROUP_NEWSFEED_FAIL',
  DELETE_GROUP:'DELETE_GROUP',
  CREATE_GROUP:'CREATE_GROUP',
  CREATE_GROUP_SUCCESSFUL:'CREATE_GROUP_SUCCESSFUL',
  CREATE_GROUP_FAIL:' CREATE_GROUP_FAIL',
  FILTER_JOINED_GROUP:'FILTER_JOINED_GROUP',
  JOIN_GROUP:'JOIN_GROUP',
  GET_PET_CATEGORY:'GET_PET_CATEGORY'
}
export const eventsTypes = {
  CREATE_EVENT_LOADER:'ADD_EVENTS_LOADER',
  CREATE_EVENT_FAIL:'CREATE_EVENT_FAIL',
  CREATE_EVENT_SUCCESSFUL:' CREATE_EVENT_SUCCESSFUL',
  EVENT_NEWS_FEED:'EVENT_NEWS_FEED',
  EVENT_NEWS_FEED_SUCCESSFUL:'EVENT_NEWS_FEED_SUCCESSFUL',
  EVENT_NEWS_FEED_FAIL:'EVENT_NEWS_FEED_FAIL'

}


function createRequestTypes(base, types = defaultTypes) {
  const res = {};
  types.forEach(type => (res[type] = `${base}_${type}`));
  return res;
}

export const APP = createRequestTypes('APP', [
  'START',
  'READY',
  'INIT',
  'SET_STACK_ROOT',
  'SET_DB',
]);

export default types;
